### ISSUE TITLE
Error in preprocess if no normcounts

### ISSUE THREAD

**Issue by lazappi** [kdkorthauer/scDD#11]
Hi Keegan

I am running into an error in `preprocess` if there is no `normcounts` assay in `SCdat`. It looks like it is caused by the following lines:

```
if (length(unique(colData(SCdat)[[condition]])) != 2 | 
     length(colData(SCdat)[[condition]]) != ncol(normcounts(SCdat))){
      stop("Error: Please specify valid condition labels.")
}
```

I think this should be easy to fix by changing `length(colData(SCdat)[[condition]]) != ncol(normcounts(SCdat))` to `length(colData(SCdat)[[condition]]) != dim(scDat)[2])`. Alternatively I'm not sure you need this check at all, I think this should be enforced by `SingleCellExperiment` but possibly not.

Thanks

Luke

**Comment by kdkorthauer** [comment]
Thanks for catching this error, Luke! Should be fixed now.

Best,
Keegan
