### ISSUE TITLE
dealing with NAs in the data matrix

### ISSUE THREAD

**Issue by AtiSal** [kdkorthauer/scDD#13]
Nice package to identify DD genes rather than traditional DE! 
I came across this package recently and I've been trying it on different datasets, including raw and normalised gene counts. _My question is whether and how scDD deals with NA values in the data matrix_? The dataset that I'm using at the moment is log-transformed and naturally there are many NAs in the data matrix. 
Look forward to hearing from you soon.

**Comment by kdkorthauer** [comment]
Hi @AtiSys,

scDD expects that the input object contains normalized counts on the original scale (not log-transformed). As a result, there should not be any transformation-induced NA values. 

Best,
Keegan
