### ISSUE TITLE
Error with small number of cells

### ISSUE THREAD

**Issue by zji90** [kdkorthauer/scDD#14]
Hi,
I try to run scDD on a small dataset where one group has 9 cells and the other group has 14 cells. There is an error message as below. I wonder how to fix that? Thanks!

Notice: 35 genes have less than 3 nonzero cells per condition.  Only testing for DZ for these genes.
Error in apply(normcounts(SCdat)[tofit, colData(SCdat)[[condition]] ==  : 
  dim(X) must have a positive length

**Comment by kdkorthauer** [comment]
Hi @zji90,

Thanks for reporting this issue. 

The message is telling you that 35 of your genes are zero in almost all cells.

I am not sure why the error is arising, so more information would be helpful. Can you tell me know many total genes you are testing? 

Best,
Keegan

**Comment by zji90** [comment]
Thanks for your reply! I am only running the program on a very small number of genes, approximately 30-40 genes. Would that cause the problem?

**Comment by kdkorthauer** [comment]
If you are running only on 36 genes, then I am pretty sure I see why the error is generated. Given the warning about 35 genes being mostly zero, this would leave only one gene to fit the multimodal models, and the naive subset procedure assumes at least two (with only one, it coerces a matrix into a vector which throws the `dim()` error). 

I have just pushed a change that should allow you to run on this small subset of genes. Please try it out (from GitHub immediately, or from Bioc devel within the next day or two) and let me know if it fixes the issue.

Best,
Keegan

**Comment by Winnie09** [comment]
That works. Thanks!

**Comment by zji90** [comment]
That works. Thanks!
