### ISSUE TITLE
Error in testZeroes()

### ISSUE THREAD

**Issue by zji90** [kdkorthauer/scDD#15]
In testZeroes() function, sometimes arm::bayesglm returns NA for condition (see warning below), which results in summary(M1)$coefficients only having two instead of three rows. 'summary(M1)$coefficients[3, 4]' will then throw an error due to wrong indexing (there is no 3rd row). Something like this may fix the error:

if (nrow(summary(M1)$coefficients)==3) {
  return(summary(M1)$coefficients[3, 4])  
} else {
  return(NA)
}

arm::bayesglm warning message:
Warning messages:
1: In bayesglm.fit(x = X, y = Y, weights = weights, start = start,  :
  non-finite coefficients at iteration 7
2: algorithm did not converge 
3: fitted probabilities numerically 0 or 1 occurred

**Comment by kdkorthauer** [comment]
Thanks for the report and suggested fix. I've updated the development version.

Best,
Keegan
