### ISSUE TITLE
scDD(..,min.size) result gives distinct number of clusters compared to results(data, type='Zhat.c2')`

### ISSUE THREAD

**Issue by erikadudki** [kdkorthauer/scDD#16]
Hi,
I have a question regarding the option `min.size` in the `scDD` function. I'm running the scDD analysis with `min.size=10`, from my understanding that would mean a cluster needs minimum 10 cells, such that it is regarded as a cluster. But when I'm looking at the cluster memberships for each cell (with `results(data, type='Zhat.c2')` for some genes there exist clusters with e.g. 2 cells and also the number of clusters is then more, than predicted from the scDD `results` object, in the column `Clusters.c2`.
For example, my result matrix looks like:
```
gene	DDcategory	Clusters.combined	Clusters.c1	Clusters.c2
gene1	DZ		1			1		2
```
and evaluating for `gene1` the number of cells belonging to a specific cluster from the `results(data, type='Zhat.c2')` gives:
```
cluster	   number_of_cells
0    	  450
2     	  38
3     	  35
1      	  2
```
which means there are 2 cells which belong to cluster 1;  450 cells belong to cluster 0 and so on...  
I'm not sure how this can happen, I thought this cluster with 2 cells should then merge to another cluster? 

Best,
Erika

**Comment by kdkorthauer** [comment]
Hi Erika,

Apologies for the late reply.

The `min.size` argument means that clusters with fewer cells than that argument are ignored for the step in which the gene is characterized into a pattern (DE, DP, DM, DB). 

Clusters are only merged if _all_ clusters have fewer than `min.size` cells. 

Hope that helps!

Best,
Keegan
