### ISSUE TITLE
Clarification on "valid conditions"

### ISSUE THREAD

**Issue by mr-september** [kdkorthauer/scDD#17]
Hi,

I am trying to run scDD on a PBMC5k dataset that's been through the "standard" Seurat pipeline, then converted to `sce`. I hope to do something like `FindAllMarkers` from Seurat, i.e. identify each cluster's own DE genes relative to the rest.

Getting this error
```
Error in scDD(data_transcripts_sce, prior_param = prior_param, testZeroes = FALSE) : 
  Error: Please specify valid condition labels.
```

To clarify, are `valid condition labels` = clusters? If so, how would one generate this `colData(SCdat)[[condition]]` column? I think Seurat clusters are in `sce@colData@listData$seurat_clusters`

**Comment by kdkorthauer** [comment]
Hi @mr-september,

'Condition' here refers to the groups that you would like to identify DE genes between. In your case that sounds one cluster versus all the rest. So you'd generate labels that indicate which cells are in the particular cluster you are testing, and which are in any other cluster. Note that you'd have to run each pairwise comparison separately. For more details, see the help file info on the `condition` argument in the `scDD` function.

Best,
Keegan
