### ISSUE TITLE
Getting Strange BiocParallel Error

### ISSUE THREAD

**Issue by compbiolover** [kdkorthauer/scDD#18]
Hi all,
I have recently started using scDD to find differentially distributed genes in an existing single-cell dataset. After following the steps in the "Identifying differential distributions in singlecell RNA-seq experiments with scDD" vignette I repeatedly run into the following BiocParallels error  when trying to run the scDD function. 

"Error: BiocParallel errors
  element index: 1, 2, 3, 4, 5, 6, ...
  first error: object '382.017' of mode 'function' was not found"

As far as I can tell my data is in the proper SingleCellExperiment format and the filtering step that occurs before this does properly filter my data (a see a big reduction in gene number). I am attaching my Rsesion info. Will be happy to provide any additional information about my data or code if needed.  Thanks in advance for the help!   
[sessionInfo.txt](https://github.com/kdkorthauer/scDD/files/5939368/sessionInfo.txt)

**Comment by kdkorthauer** [comment]
Hi @compbiolover,

Thanks for reporting this. I'm not sure what is causing this error - as a first step, can you please check the output of `BiocManager::valid()` and make sure that all packages are compatible with the version of Bioconductor you are using?

**Comment by compbiolover** [comment]
Hi @kdkorthauer ,

Thanks for getting back to me. I just ran` BiocManager::valid()` and got the output attached below. I noticed that it reported that I had some packages out of date. I updated them and re-ran my code and still got the same error as before. 
![bioconductor-valid-output](https://user-images.githubusercontent.com/39838470/107860951-88e25b00-6e10-11eb-8c5f-79ac7d12b43b.png)
![bioconductor-out-of-date-packages](https://user-images.githubusercontent.com/39838470/107860952-897af180-6e10-11eb-83da-e8d6fc8dd854.png)

**Comment by kdkorthauer** [comment]
Thanks - just to confirm, the output of `BiocManager::valid()` now reports that 0 packages are out of date?

**Comment by compbiolover** [comment]
Yes, that is correct. Would you like for me to upload my `SingleCellExperiment` object for you to examine? Maybe something about my data is wonky.

Also, I ran `traceback()` and got the following output. I also posted this question in the `BiocParallels` issue tracker, and they mentioned it might be a data alignment issue (probably with my data). I have set `BiocParallels` to run sequentially (i.e., without multiple cores), and I still get the same error. This makes me think it is an issue of the data.  
![scDD-related-code](https://user-images.githubusercontent.com/39838470/107864500-b3d9a880-6e2a-11eb-9bf5-a232458aaa25.png)
![traceback-output](https://user-images.githubusercontent.com/39838470/107864442-21d1a000-6e2a-11eb-872f-780bb5d70e9d.png)

**Comment by kdkorthauer** [comment]
That would be great; if there's a small subset of your object that throws the same error, that would be best. Let me know if you'd like a dropbox link to upload to. I can make one.

**Comment by compbiolover** [comment]
I reproduced the same kind of error on a subset of the dataset (17 genes by 10 cells [5 in condition 1 and 5 in condition 2] after the filtering step). This happened whether it was in multi-core mode or single-core mode. Note: it looks like the error given by the single-core mode is slightly different from the multi-core mode. They both share the "object x of mode 'function' was not found" component, though. I will be happy to upload the subset files and my code to a dropbox link for you.

**Comment by kdkorthauer** [comment]
Great! Here is a link:
https://www.dropbox.com/request/PK9TVgZqRPLX6D1K1xr3

**Comment by compbiolover** [comment]
Fantastic! I just uploaded the files.

**Comment by compbiolover** [comment]
Good news! I got it working. One of my preprocessing steps was not applying a transformation the way I thought it was. This issue can be closed. Thanks for all of your help!

**Comment by kdkorthauer** [comment]
Oh, that's great! Thanks for letting me know.
