### ISSUE TITLE
scDD on Bioconductor?

### ISSUE THREAD

**Issue by lazappi** [kdkorthauer/scDD#5]
Hi

I was just wondering if you have considered submitting scDD to Bioconductor?

I have been working on a package which I have submitted which uses a couple of functions in scDD. They don't allow you to depend on packages that are only on Github though so at the moment it looks as though I will have to drop that functionality.

Details of the submission process are [here](https://www.bioconductor.org/developers/package-submission/) and the Bioconductor maintainers are good at walking people through it. As well as helping me out I think it would have some benefits for you in terms of advertising scDD and making it more accessible. 

Cheers

**Comment by kdkorthauer** [comment]
Hi @lazappi,

Yes, submitting scDD to Bioconductor is on my to-do list.  I was not aware that Bioconductor packages cannot depend on packages that are only in GitHub, so thanks for making me aware of this time-sensitive issue.  I'm making this a top priority and will submit as soon as I can.  I'll close this issue once I do submit, so you'll know that the process has been started.  Thanks again for bringing this to my attention.

Best,
Keegan

**Comment by lazappi** [comment]
Great, thanks! I look forward to seeing scDD on Bioconductor.

**Comment by kdkorthauer** [comment]
Just submitted to Bioconductor!  You can follow its progress in the Bioconductor/Contributions repository, and I can send you a message letting you know when it has been accepted.  I'm closing this issue now.

Best,
Keegan

**Comment by kdkorthauer** [comment]
Hi @lazappi,

Just wanted to update you on the progress in getting scDD into Bioconductor.  The package has been accepted and now I'm just waiting for my SVN credentials.  Hopefully your package will have smooth sailing now.  

Thanks again for the extra push to get this taken care of.

Best,
Keegan

**Comment by lazappi** [comment]
Congratulations! Now I just have to find some time to finish my submission.
