### ISSUE TITLE
bpparam in simulateSet

### ISSUE THREAD

**Issue by lazappi** [kdkorthauer/scDD#9]
Hi

Would it be possible to add a `bpparam` parameter to `simulateSet`, similar to the one in the `scDD` function? There is a `bplapply` in the `findIndex` function and at the moment there is no way to control how many cores it uses which is causing me some problems.

Thanks

Luke

**Comment by kdkorthauer** [comment]
Hi Luke,

Great suggestion! I have added the `param` parameter to the `simulateSet` function, which works in the same way as in the `scDD` function. Hopefully this solves the problems you were encountering and thanks for bringing it to my attention!

Best,
Keegan

**Comment by lazappi** [comment]
Thanks for doing this. Just wanted to let you know that it doesn't seem to have transferred to Bioconductor properly. You can see the new argument in the manual on the website but not locally when you install via biocLite. I have downloaded the source and it seems to be missing from that as well. A new commit might make it sync up, or the Bioc people might have other ideas?

**Comment by kdkorthauer** [comment]
Hi Luke,

Thanks for letting me know about this! I believe the issue of biocLite() being behind the bioconductor-mirror GitHub repo and the ref manual was because I neglected to include a version bump with that update.  I have just committed a version bump, so the updates should be reflected in biocLite() soon.

Apologies for the oversight; I am still trying to get the hang of the git-svn workflow.  

Best,
Keegan

**Comment by lazappi** [comment]
Cool. That makes sense but still seems a bit weird that it picked up the documentation and nothing else. The git-svn thing can be tricky, hopefully it will be easier when they switch over to straight git.

**Comment by kdkorthauer** [comment]
Agreed. Can't wait for transition! 

It seems that what is reflected in the documentation on the landing page and what is accessible through biocLite() is different. From the bioconductor version numbering [help page](https://www.bioconductor.org/developers/how-to/version-numbering/):

>Changes made to SVN without a corresponding version bump do not propagate to the repository visible to biocLite().
